=== Jon-Maneiro/SuperProyecto/XML/Classification.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="classification" type="classification_type"/>
    <xs:complexType name="classification_type">
        <xs:sequence>
            <xs:element name="team" type="team_type" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="team_type">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="points" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>

=== Jon-Maneiro/SuperProyecto/XML/Classification.xml
<?xml version="1.0" encoding="UTF-8"?>
<classification xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Classification.xsd">
    <team>
        <name/>
        <points>0</points>
    </team>
    <team>
        <name/>
        <points>0</points>
    </team>
    <team>
        <name/>
        <points>0</points>
    </team>
    <team>
        <name>Rua</name>
        <points>12</points>
    </team>
    <team>
        <name>Kolme</name>
        <points>12</points>
    </team>
    <team>
        <name>Papat</name>
        <points>12</points>
    </team>
    <team>
        <name>Bost</name>
        <points>12</points>
    </team>
    <team>
        <name>Isii</name>
        <points>12</points>
    </team>
    <team>
        <name>Seachd</name>
        <points>12</points>
    </team>
    <team>
        <name>Eight</name>
        <points>12</points>
    </team>
    <team>
        <name>Aon</name>
        <points>28</points>
    </team>
    <team>
        <name>Aon</name>
        <points>28</points>
    </team>
    <team>
        <name>Rua</name>
        <points>12</points>
    </team>
    <team>
        <name>Kolme</name>
        <points>12</points>
    </team>
    <team>
        <name>Papat</name>
        <points>12</points>
    </team>
    <team>
        <name>Bost</name>
        <points>12</points>
    </team>
    <team>
        <name>Isii</name>
        <points>12</points>
    </team>
    <team>
        <name>Seachd</name>
        <points>12</points>
    </team>
    <team>
        <name>Eight</name>
        <points>12</points>
    </team>
    <team>
        <name>Aon</name>
        <points>28</points>
    </team>
    <team>
        <name>Rua</name>
        <points>12</points>
    </team>
    <team>
        <name>Kolme</name>
        <points>12</points>
    </team>
    <team>
        <name>Papat</name>
        <points>12</points>
    </team>
    <team>
        <name>Bost</name>
        <points>12</points>
    </team>
    <team>
        <name>Isii</name>
        <points>12</points>
    </team>
    <team>
        <name>Seachd</name>
        <points>12</points>
    </team>
    <team>
        <name>Eight</name>
        <points>12</points>
    </team>
</classification>
<!--<!DOCTYPE classification SYSTEM "Classification.dtd">-->
