=== Jon-Maneiro/SuperProyecto/XML/League.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="league" type="league_type"/>

    <xs:complexType name="league_type">
        <xs:sequence>
            <xs:element name="matchset" type="matchset_type" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="matchset_type">
        <xs:sequence>
            <xs:element name="match" type="match_type" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="match_type">
        <xs:sequence>
            <xs:element name="team1" type="xs:string"/>
            <xs:element name="team2" type="xs:string"/>
            <xs:element name="score1" type="xs:string" minOccurs="0"/>
            <xs:element name="score2" type="xs:string" minOccurs="0"/>
            <xs:element name="date" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute type="xs:ID" name="id"/>
    </xs:complexType>
</xs:schema>

=== Jon-Maneiro/SuperProyecto/XML/Leaguebase.xml
<?xml version="1.0" encoding="utf-8" ?>
<!--<!DOCTYPE league SYSTEM "League.dtd">-->
<league xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		  xsi:noNamespaceSchemaLocation="League.xsd">
	<updatedate>1997/01/01</updatedate>
	<matchset>
		<match id="a">
			<team1></team1>
			<team2></team2>
			<score1>0</score1>
			<score2>0</score2>
		</match>
		<match id="b">
			<team1></team1>
			<team2></team2>
			<score1>0</score1>
			<score2>0</score2>
		</match>
	</matchset>
	<matchset>
		<match id="c">
			<team1></team1>
			<team2></team2>
		</match>
		<match id="d">
			<team1></team1>
			<team2></team2>
		</match>
</matchset>
</league>

=== Jon-Maneiro/SuperProyecto/XML/League.xml
<?xml version="1.0" encoding="UTF-8"?>
<league xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="League.xsd">
    <updatedate>1997-01-01</updatedate>
    <matchset>
        <match id="1">
            <team1>Aon</team1>
            <team2>Rua</team2>
            <score1>0</score1>
            <score2>0</score2>
        </match>
        <match id="2">
            <team1>Kolme</team1>
            <team2>Isii</team2>
            <score1>0</score1>
            <score2>0</score2>
        </match>
        <match id="3">
            <team1>Papat</team1>
            <team2>Bost</team2>
            <score1>0</score1>
            <score2>0</score2>
        </match>
    </matchset>
    <matchset>
        <match id="4">
            <team1>Aon</team1>
            <team2>Kolme</team2>
            <score1>0</score1>
            <score2>0</score2>
        </match>
        <match id="5">
            <team1>Rua</team1>
            <team2>Papat</team2>
            <score1>0</score1>
            <score2>0</score2>
        </match>
        <match id="6">
            <team1>Bost</team1>
            <team2>Isii</team2>
            <score1>0</score1>
            <score2>0</score2>
        </match>
    </matchset>
    <matchset>
        <match id="7">
            <team1>Aon</team1>
            <team2>Papat</team2>
            <score1>0</score1>
            <score2>0</score2>
        </match>
        <match id="8">
            <team1>Kolme</team1>
            <team2>Bost</team2>
            <score1>0</score1>
            <score2>0</score2>
        </match>
        <match id="9">
            <team1>Rua</team1>
            <team2>Isii</team2>
            <score1>0</score1>
            <score2>0</score2>
        </match>
    </matchset>
    <matchset>
        <match id="10">
            <team1>Aon</team1>
            <team2>Bost</team2>
            <score1>0</score1>
            <score2>0</score2>
        </match>
        <match id="11">
            <team1>Papat</team1>
            <team2>Isii</team2>
            <score1>0</score1>
            <score2>0</score2>
        </match>
        <match id="12">
            <team1>Rua</team1>
            <team2>Kolme</team2>
            <score1>0</score1>
            <score2>0</score2>
        </match>
    </matchset>
    <matchset>
        <match id="13">
            <team1>Aon</team1>
            <team2>Isii</team2>
            <score1>0</score1>
            <score2>0</score2>
        </match>
        <match id="14">
            <team1>Rua</team1>
            <team2>Bost</team2>
            <score1>0</score1>
            <score2>0</score2>
        </match>
        <match id="15">
            <team1>Kolme</team1>
            <team2>Papat</team2>
            <score1>0</score1>
            <score2>0</score2>
        </match>
    </matchset>
    <matchset>
        <match id="16">
            <team1>Rua</team1>
            <team2>Aon</team2>
            <score1>0</score1>
            <score2>0</score2>
        </match>
        <match id="17">
            <team1>Isii</team1>
            <team2>Kolme</team2>
            <score1>0</score1>
            <score2>0</score2>
        </match>
        <match id="18">
            <team1>Bost</team1>
            <team2>Papat</team2>
            <score1>0</score1>
            <score2>0</score2>
        </match>
    </matchset>
    <matchset>
        <match id="19">
            <team1>Kolme</team1>
            <team2>Aon</team2>
            <score1>0</score1>
            <score2>0</score2>
        </match>
        <match id="20">
            <team1>Papat</team1>
            <team2>Rua</team2>
            <score1>0</score1>
            <score2>0</score2>
        </match>
        <match id="21">
            <team1>Isii</team1>
            <team2>Bost</team2>
            <score1>0</score1>
            <score2>0</score2>
        </match>
    </matchset>
    <matchset>
        <match id="22">
            <team1>Papat</team1>
            <team2>Aon</team2>
            <score1>0</score1>
            <score2>0</score2>
        </match>
        <match id="23">
            <team1>Bost</team1>
            <team2>Kolme</team2>
            <score1>0</score1>
            <score2>0</score2>
        </match>
        <match id="24">
            <team1>Isii</team1>
            <team2>Rua</team2>
            <score1>0</score1>
            <score2>0</score2>
        </match>
    </matchset>
    <matchset>
        <match id="25">
            <team1>Bost</team1>
            <team2>Aon</team2>
            <score1>0</score1>
            <score2>0</score2>
        </match>
        <match id="26">
            <team1>Isii</team1>
            <team2>Papat</team2>
            <score1>0</score1>
            <score2>0</score2>
        </match>
        <match id="27">
            <team1>Kolme</team1>
            <team2>Rua</team2>
            <score1>0</score1>
            <score2>0</score2>
        </match>
    </matchset>
    <matchset>
        <match id="28">
            <team1>Isii</team1>
            <team2>Aon</team2>
            <score1>0</score1>
            <score2>0</score2>
        </match>
        <match id="29">
            <team1>Bost</team1>
            <team2>Rua</team2>
            <score1>0</score1>
            <score2>0</score2>
        </match>
        <match id="30">
            <team1>Papat</team1>
            <team2>Kolme</team2>
            <score1>0</score1>
            <score2>0</score2>
        </match>
    </matchset>
</league>
<!--<!DOCTYPE league SYSTEM "League.dtd">-->
